---
- name: Scaling ceph-storage nodes down and up again
  hosts: undercloud
  become: yes
  become_user: "{{ installer.user.name }}"
  gather_facts: no
  roles:
      - {role: "installer/tripleo/overcloud/scale/", service: 'ceph-storage', amount: 1}
      - {role: "installer/tripleo/overcloud/scale/", service: 'ceph-storage', amount: 3}
